#      _   _____   ___   _  _  ___ ___ ___  _  _____ ___ ___
#     /_\ |   \ \ / /_\ | \| |/ __| __|   \| |/ / __| __| _ \
#    / _ \| |) \ V / _ \| .` | (__| _|| |) | ' <| _|| _||  _/
#   /_/ \_\___/ \_/_/ \_\_|\_|\___|___|___/|_|\_\___|___|_|
#


# Plugin messaging prefix
message_prefix: "&cAdvancedKeep > &f"

# Do you allow this plugin to check for new updates?
check_update: true


# Configuration for soul gem
soul_gem:
  # The soul gem item
  # Read how to configure the item here:
  # https://anhcraft.dev/cd/craftkit/PreparedItem.schema.html
  item:
    material: EMERALD
    name: "&6&lSoul &a&lGem"
    lore:
      - "&fSave your items one-time!"
    enchant:
      durability: 1
    flag:
      - hide_enchants

  # The name of the NBT tag which KML uses to determine an item is the soul gem
  # Do not change this if your players have already used any soul gems
  nbt_tag: "kml_soul_gem"

  # Recipe to craft the soul gem
  recipe:
    enable: false
    shape:
      - "ABA"
      - "BCB"
      - "ABA"
    ingredients:
      - "A emerald"
      - "B blaze_powder"
      - "C nether_star"

  # Messages to be sent after using the gem
  messages_on_use:
    - "&aYou've used &6&lSoul &a&lGem"

  # Commands to be executed after using the gem
  commands_on_use:
    - "give {player} apple 1"


# Configuration for death chest
death_chest:
  # If another chest exists, should we merge items or replace the chest?
  merge_chest_on_duplicate: true

  # Should we lock the death chest? So only the owner is able to open.
  lock_death_chest: true

  # Show signal effect near the death chest?
  # The signal is useful for players to find the chest
  signal_effect: true

  # The material of the death chest
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  material: chest


# Configuration for world groups
world_groups:
  # First group
  group1: # <-- Set to anything you want (its just an identifier)
    # List of worlds in this group
    worlds:
      - abcxyz

    # Keep inventories based on Minecraft time (https://minecraft.gamepedia.com/Day-night_cycle)
    time_keep:
      # This is day settings
      day: # <-- Set to anything you want (its just an identifier)
        # The duration when this time-keep is activated in the group
        # The unit is Minecraft ticks (20 ticks = 1 second)
        # - All day: from 0 to 24000
        # - Day: from 0 to 12516
        # - Night: from 12516 to 24000
        from: 0
        to: 12516

        # Should we keep the items at this duration?
        keep_item: true

        # Should we keep exp points?
        keep_exp: true

        # The sound to be played when this time-keep is activated
        # 1.15: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
        # 1.14: https://jd.andross.fr/spigot-1.14.4-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        # 1.13: https://jd.andross.fr/spigot-1.13.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        # 1.12: https://jd.andross.fr/spigot-1.12.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        # 1.11: https://jd.andross.fr/spigot-1.11.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        # 1.10: https://jd.andross.fr/spigot-1.10.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        # 1.9: https://jd.andross.fr/spigot-1.9.4-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
        #sound: ""

        # Messages to be announced when this time-keep is activated
        broadcast:
          chat:
            - "&a&lGood morning! Keep inventory enabled."
          action_bar: "&aKeep inventory enabled! You are safe now."

      # This is night settings
      night:
        from: 12516
        to: 24000
        keep_item: false
        keep_exp: true
        broadcast:
          chat:
            - "&c&lOops... It is night! Keep inventory disabled :<"
          action_bar: "&cBe careful with your items!"

        # Enable death chest feature
        enable_death_chest: true

        # Allow players to use soul gems
        allow_soul_gem: true

        # *** Lands integration ***
        # (If you don't have Lands, just ignore or remove these settings)
        # 4 settings below are set to false by default
        lands:
          # - You don't lose your items if you are in your own/trusted area
          keep_items_in_areas: true

          # - You don't lose your items if you are in wilderness
          keep_items_in_wilderness: false

          # - You don't lose your exp points if you are in your own/trusted area
          keep_exp_in_areas: true

          # - You don't lose your exp points if you are in wilderness
          keep_exp_in_wilderness: false

        # *** Towny integration ***
        # (If you don't have Towny, just ignore or remove these settings)
        towny:
          # - You don't lose your items if you are in your own/joined town
          keep_items_in_town: true

          # - You don't lose your items if you are in wilderness
          keep_items_in_wilderness: false

          # - You don't lose your exp points if you are in your own/joined town
          keep_exp_in_town: true

          # - You don't lose your exp points if you are in wilderness
          keep_exp_in_wilderness: false

        # *** Factions integration ***
        # Support plugin: SaberFaction
        # (If you don't have any of those plugins, just ignore or remove these settings)
        faction:
          # - You don't lose your items if you are in your own/joined faction
          keep_items_in_faction: true

          # - You don't lose your items if you are in wilderness
          keep_items_in_wilderness: false

          # - You don't lose your exp points if you are in your own/joined faction
          keep_exp_in_faction: true

          # - You don't lose your exp points if you are in wilderness
          keep_exp_in_wilderness: false

  # Second group
  group2:
    worlds:
      - example_world
    time_keep:
      "0":
        # Keep all day!
        from: 0
        to: 24000
        keep_item: true
