

#     ,--. ,--.                     ,--.   ,--.         ,--.   ,--. ,---.
#     |  .'   / ,---.  ,---.  ,---. |   `.'   |,--. ,--.|  |   `--'/  .-' ,---.
#     |  .   ' | .-. :| .-. :| .-. ||  |'.'|  | \  '  / |  |   ,--.|  `-,| .-. :
#     |  |\   \\   --.\   --.| '-' '|  |   |  |  \   '  |  '--.|  ||  .-'\   --.
#     `--' '--' `----' `----'|  |-' `--'   `--'.-'  /   `-----'`--'`--'   `----'
#                            `--'              `---'

# Plugin messaging prefix
message_prefix: "&bKML: &f"
# Do you allow this plugin to check for new updates?
check_update: true


# Configuration for soul gem
soul_gem:
  # This section uses ABIF (anhcraft's bukkit item format)
  # Reference: https://github.com/anhcraft/ABIF/blob/master/README.md
  item:
    material: EMERALD
    name: "&6&lSoul &a&lGem"
    lore:
      - "&fEach gem can save your items one time!"
    enchant:
      durability: 1
    flag:
      - hide_enchants

  # The name of the NBT tag which KML uses to determine an item is the soul gem
  # Do not change this if your players have already used the soul gems
  nbt_tag: "kml_soul_gem"


# Configuration for world groups
world_groups:
  # First group
  group1:
    # List of worlds in this group
    worlds:
      - abcxyz
    allow_soul_gem: true # all worlds in this group allow players to use soul gems
    # Keep inventories based on Minecraft time (https://minecraft.gamepedia.com/Day-night_cycle)
    time_keep:
      # This is day settings
      day: # <-- you can change the name
        from: 0
        to: 12516 # in Minecraft ticks
        keep_item: true # it means: Over the day at "abcxyz" world, all lost items will be kept
        keep_level: true # keep player level
        sound: "entity_firework_twinkle" # case-insensitive | for 1.13+: ENTITY_FIREWORK_ROCKET_TWINKLE
        broadcast:
          # these messages will appear on players chat box
          chat:
            - "&a&lGood morning! Keep inventory enabled."
      # This is night settings
      night:
        from: 12516
        to: 24000
        keep_item: false # it means: Over the night at "abcxyz" world, all items will not be kept
        keep_level: true
        sound: "ENTITY_ENDERDRAGON_AMBIENT" # for 1.13+: ENTITY_ENDER_DRAGON_AMBIENT
        broadcast:
          chat:
            - "&c&lOops... It is night! Keep inventory disabled :<"
          # below message will appear on players action bar
          action_bar: "&cBe careful with your items!"

  # Second group
  group2:
    worlds:
      - example
    # This option overrides the one above
    allow_soul_gem: true # Now, only the "example" world does not allow the soul gems, others still allow
    time_keep:
      "0":
        # 0 to 2400 means "the whole day"
        from: 0
        to: 24000
        keep_item: true # <-- always keep xD
