

#     ,--. ,--.                     ,--.   ,--.         ,--.   ,--. ,---.
#     |  .'   / ,---.  ,---.  ,---. |   `.'   |,--. ,--.|  |   `--'/  .-' ,---.
#     |  .   ' | .-. :| .-. :| .-. ||  |'.'|  | \  '  / |  |   ,--.|  `-,| .-. :
#     |  |\   \\   --.\   --.| '-' '|  |   |  |  \   '  |  '--.|  ||  .-'\   --.
#     `--' '--' `----' `----'|  |-' `--'   `--'.-'  /   `-----'`--'`--'   `----'
#                            `--'              `---'



# === GENERAL ===

general:
  # plugin's message prefix
  prefix: "&b[KML] "
  # should notify the players when a new version available?
  notify_update: true


# === KEEP RUNE ===
# a rune which keeps all items of player one time!
# after used, the rune will be removed
# If your server uses DeathDropsAPI, the messages of keep rune feature won't work

keep_rune:
  recipe:
    # can players craft runes?
    enable: true
    shape:
    - "ABA"
    - "BCB"
    - "ABA"
    materials:
    - "A 388:0"
    - "B 377:0"
    - "C 399:0"

  # adds the world which you want to use this feature here:
  worlds:
  - world
  - world_nether

  # a chat message to send to the player when a keep rune was used
  chat:
    enable: true
    message: "&aYour items were saved by keep rune :D"

  # a title message to send to the player when a keep rune was used
  title:
    enable: false
    title: "&aWelcome back!"
    subtitle: "&6Used keep rune"

  # an action bar message to send to the player when a keep rune was used
  actionbar:
    enable: false
    message: ""

  item:
    name: "&a&lKeep &e&lRune"
    material: EMERALD
    durability: 0
    lores:
    - "&fAn useful rune will keep your life one time!"
    - "&cJust put this item in your inventory"
    - "&f"
    - "&f-= KeepMylife =-"
    enchants:
    - DURABILITY:1
    unbreakable: true
    hide_unbreakable: true
    hide_enchants: true

    # NBT Tag to determine an item is a keep rune
    # Don't change this if your players've already used keep runes
    nbt_tag: "keepmylife_keeprune"





# === DAY/NIGHT ===
# keep items of players depends on the time of their world

keep_items_daynight:
  # if you want to keep at night, change this to "night"
  keep_time: day

  # time ended the morning and start the evening
  # WARNING: this plugin uses Minecraft ticks
  #
  # 1000: Time when using the /time set day command.
  # 6000: Noon; the sun is at its zenith.
  # 13000: Time when using the /time set night command.
  # 18000: Midnight; the moon is at its zenith.
  #
  # http://minecraft.gamepedia.com/Day-night_cycle
  time_begin_night: 13000

  # sound
  sound:
    enable: true
    # 1.8 sound: FIREWORK_TWINKLE
    keep: "ENTITY_FIREWORK_TWINKLE"
    # 1.8 sound: ENDERDRAGON_GROWL
    nonkeep: "ENTITY_ENDERDRAGON_AMBIENT"

  # list of world which you want to use this feature
  worlds:
  - "world"
  # - "example"
  # - "server"
  # - "survival"

  # chat messages to broadcast to anyone in the world
  messages:
    enable: true
    keep: "&6Now is the morning, kept items in &c<world> &6!"
    nonkeep: "&6Now is the evening, non-kept items in &c<world> &6!"

  # title messages to send to anyone in the world
  title:
    enable: true
    keep:
      title: "&aNow is the morning!"
      subtitle: "&fKept all player's items :)"
    nonkeep:
      title: "&aNow is the evening!"
      subtitle: "&fNon-kept all player's items :("

  # action bar messages to send to anyone in the world
  actionbar:
    enable: false
    keep: "&cKept item!"
    nonkeep: "&cNon-kept item!"





# === WHITELIST ===
# always keeps in a specific world

keep_items_whitelist:
- "protected_world"
#- "world_nether"
#- "world_the_end"





# === KEEP ITEMS FILTER ===
# always keeps specific items

keep_items_filter:
  world:
    '0':
      material: EMERALD
      durability: 0
    '1':
      material: DIAMOND
      durability: 0
      name: '&a&lProtected Item'
    '2':
      material: DIAMOND
      durability: 0
      contains_lore: '&c&l[Protected]'
    '3':
      material: DIAMOND
      durability: 0
      # this chance must from 0 to 1, ex: 0.2 means 20% of chance this item won't keep even it passes all requirements
      fail_chance: 0.2